package org.hajecsdb.graphs.transactions.transactionalGraph;

public enum CRUDType {
    CREATE_NODES_PROPERTY, READ_NODES_PROPERTY, UPDATE_NODES_PROPERTY, DELETE_NODES_PROPERTY,
    CREATE_RELATIONSHIPS_PROPERTY, UPDATE_RELATIONSHIPS_PROPERTY
}
